server:
  max-http-header-size: 4048576
  tomcat:
    max-http-form-post-size: 1000MB
  port: 8081
#  servlet:
#    context-path: /bug-parser-test

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB  #单个文件的最大上限
      max-request-size: 1000MB #单个请求的文件总大小上限

  # 配置数据源
  datasource:
    username:
    password:
    # 服务器测试数据库
#    url: jdbc:sqlite:/export/nisl/ty/temp/result.db

#    # 服务器正式数据库
    url: jdbc:sqlite:/export/nisl/yhy/mutationData/qx_1st/workspace/result/result.db

    # 本地测试数据库
#    url: jdbc:sqlite:C:\临时\5-25\result_5_20_test.db
    driver-class-name: org.sqlite.JDBC

  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/

#
logging:
  file:
#    name: C:\临时\5-25\logging.txt
#    name: /export/nisl/ty/temp/logger/test.log
    name: /export/nisl/ty/temp/logger/production.log
  level:
    root: warn


# mybatis配置
mybatis:
  type-aliases-package: com.ty.bugparser.pojo
  mapper-locations: classpath:com/ty/bugparser/mapper/*.xml
#  config-location: 这是mybatis的配置文件，依然可以保留