server:
  max-http-header-size: 4048576
  tomcat:
    max-http-form-post-size: 1000MB
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB  #单个文件的最大上限
      max-request-size: 1000MB #单个请求的文件总大小上限

logging:
  file:
    name: /export/nisl/ty/temp/logger/spring-boot-logger.log
  level:
    root: warn
